### ISSUE TITLE
topnav

### ISSUE THREAD

**Issue by dishanique** [fridarode/autism_helpers#9]
index.html and gallery.html should have topnav in the body, not the head.

<div class=“topnav”>
       <a href=“index.html”>Home</a>
       <a href=“about.html”>About</a>
             <a href=“gallery.html”>Gallery</a>
         </div>

**Comment by Briana-t-p** [comment]
Top nav is within the body tag, which is within the header tag not the head tag. 
<body>
    <header class="background-image">
        <div>
            <h1 class="page-header-2">Autism Matters</h1>
        </div>
        <div class="topnav-li">
            <ul class="topnav-ul">
                <li><a href="gallery.html">Gallery</a></li>
                <li><a href="about.html">About</a></li>
                <li><a href="index.html">Home</a></li>
            </ul>
        </div>
        <div class="container-ceilng">
        </div>
    </header>
    <main class="main-content">

**Comment by fridarode** [comment]
Nice work!
